apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 80
          name: 80tcp01
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/upstream
          name: vol1
          subPath: upstream
        - mountPath: /etc/nginx/conf.d/default.conf
          name: vol1
          subPath: default.conf
        - mountPath: /etc/nginx/nginx.conf
          name: vol1
          subPath: nginx.conf
      volumes:
      - configMap:
          defaultMode: 256
          name: {{ .Values.configmap.name }} 
          optional: false
        name: vol1
