version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD="gsmcredis"
      - TZ="Asia/Shanghai"
    ports:
      - '6389:6379'

  tomcat_vue:
    image: harbor.net/zb/zb_web_tomcat
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 4096M
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "../zb_server/config.properties:/usr/local/tomcat/webapps/CODE/WEB-INF/classes/config.properties"
      - "../zb_server/init.properties:/usr/local/tomcat/webapps/CODE/WEB-INF/classes/init.properties"
      - "../zb_server/log4j.properties:/usr/local/tomcat/webapps/CODE/WEB-INF/classes/log4j.properties"
      - "../zb_server/context.xml:/usr/local/tomcat/conf/context.xml"
      - "/home/data/logs/zb_server/:/usr/local/tomcat/logs/"
      - "../zb_server/lib/commons-pool2-2.2.jar:/usr/local/tomcat/lib/commons-pool2-2.2.jar"
      - "../zb_server/lib/jedis-2.5.1.jar:/usr/local/tomcat/lib/jedis-2.5.1.jar"
      - "../zb_server/lib/tomcat8.5-redis-session-manager.jar:/usr/local/tomcat/lib/tomcat8.5-redis-session-manager.jar"

  nginx_frontend:
    image: harbor.net/zb/zb_web_nginx
    ports:
      - "8888:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure 
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - '/home/data/logs/zb_nginx/:/var/log/nginx/'

  nginx:
    image: harbor.net/zb/nginx
    ports:
      - "80:80"
      - "443:443"
      - "6226:6226"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure 
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - '../zb_nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '../zb_nginx/conf.d:/etc/nginx/conf.d'
      - '../zb_nginx/conf.d/crt:/etc/nginx/conf.d/crt'
      - '../zb_nginx/conf.d/vhost:/etc/nginx/conf.d/vhost'
      - '../zb_nginx/conf.d/data.txt:/etc/nginx/html/data.txt'
      - '/home/data/logs/nginx/:/var/log/nginx/'    
