replicaCount: 1

image:
  repository: 69.172.86.202/rancher/zb-web-redis
  tag: test
  pullPolicy: Always 


service:
  name: "zb-web-redis"
  type: ClusterIP
  port: 6379

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
